import { Service, Style, Salon, Stylist, TimeSlot, Booking, User } from './atoms';

export const services: Service[] = [
  {
    id: 's1',
    name: 'Haircut',
    description: 'Professional haircut tailored to your style',
    duration: 30,
    basePrice: 300,
    availableGenders: ['Male', 'Female', 'Unisex'],
    image: "/style-classic-fade.jpg"
  },
  {
    id: 's2',
    name: 'Coloring',
    description: 'Expert hair coloring and dyeing services',
    duration: 90,
    basePrice: 250,
    availableGenders: ['Female', 'Unisex'],
    image: "/style-blonde.png"
  },
  {
    id: 's3',
    name: 'Styling',
    description: 'Professional styling for special occasions',
    duration: 60,
    basePrice: 350,
    availableGenders: ['Female', 'Unisex'],
    image: "/style-waves.jpg"
  },
  {
    id: 's4',
    name: 'Massage',
    description: 'Relaxing massage therapy',
    duration: 60,
    basePrice: 350,
    availableGenders: ['Male', 'Female', 'Unisex'],
    image: "/chair-massage-ladies.jpg"
  },
  {
    id: 's5',
    name: 'Facial',
    description: 'Rejuvenating facial treatments',
    duration: 45,
    basePrice: 300,
    availableGenders: ['Female', 'Unisex'],
    image: "/classic-facial.jpeg"
  },
  {
    id: 's6',
    name: 'Waxing',
    description: 'Professional waxing services',
    duration: 30,
    basePrice: 250,
    availableGenders: ['Female', 'Unisex'],
    image: "/soft-wax.jpeg"
  },
];

export const allStyles: any = {
  Haircut:[
      {
        id: 'st1',
        serviceId: 's1',
        name: 'Classic Fade',
        description: 'Timeless fade with clean lines',
        image: '/style-classic-fade.jpg',
        price: 450,
        availableGenders: ['Male', 'Unisex'],
        rating: 4.8,
        reviews: 245,
      },
      {
        id: 'st2',
        name: 'Textured Top',
        description: 'Modern textured cut with volume',
        image: '/style-textured.jpg',
        serviceId: 's1',
        price: 500,
        availableGenders: ['Male', 'Unisex'],
        rating: 4.7,
        reviews: 205,
      },
      {
        id: 'st3',
        name: 'Luxury Bob',
        description: 'Elegant bob cut for sophistication',
        image: '/style-bob.jpg',
        serviceId: 's1',
        price: 550,
        availableGenders: ['Female', 'Unisex'],
        rating: 4.0,
        reviews: 145,
      },
      {
        id: 'st19',
        name: 'Wolf Cut',
        description: 'Elegant bob cut for sophistication',
        image: '/service-1.jpg',
        serviceId: 's1',
        price: 650,
        availableGenders: ['Unisex'],
        rating: 4.0,
        reviews: 145,
      },
  ],
  Coloring: [
      {
        id: 'st4',
        name: 'Balayage',
        description: 'Sun-kissed natural looking highlights',
        image: '/style-balayage.jpg',
        serviceId: 's2',
        price: 320,
        availableGenders: ['Female', 'Unisex'],
        rating: 4.1,
        reviews: 145,
      },
      {
        id: 'st5',
        name: 'Blonde Highlights',
        description: 'Radiant blonde highlights',
        image: '/style-blonde.png',
        serviceId: 's2',
        price: 200,
        availableGenders: ['Female', 'Unisex'],
        rating: 3.9,
        reviews: 25,
      },
      {
        id: 'st12',
        name: 'coloring men hair',
        description: 'coloring men hair',
        image: '/coloring-men-hair.png',
        serviceId: 's2',
        price: 150,
        availableGenders: [ 'Male'],
        rating: 4.3,
        reviews: 110,
      },
      {
        id: 'st13',
        name: 'coloring-hair',
        description: 'coloring-hair',
        image: '/coloring-hair.jpg',
        serviceId: 's2',
        price: 250,
        availableGenders: ['Female', 'Unisex'],
        rating: 4.1,
        reviews: 380,
      },
  ],
  Styling:[
    {
      id: 'st6',
      name: 'Bridal Styling',
      description: 'Elegant styling for your special day',
      image: '/style-bridal.png',
      serviceId: 's3',
      price: 850,
      availableGenders: ['Female', 'Unisex'],
      rating: 4.7,
      reviews: 247,
    },
    {
      id: 'st7',
      name: 'Evening Waves',
      description: 'Glamorous wavy styling for events',
      image: '/style-waves.jpg',
      serviceId: 's3',
      price: 550,
      availableGenders: ['Female', 'Unisex'],
      rating: 4.2,
      reviews: 285,
    },
  ],
  Massage:[
{
    id: 'st8',
    name: 'Chair Massage',
    description: 'chair-massage-gents',
    image: '/chair-massage-gents.webp',
    serviceId: 's4',
    price: 150,
    availableGenders: ['Male'],
    rating: 4.8,
    reviews: 225,
  },
    {
    id: 'st9',
    name: 'Chair Massage',
    description: 'chair massage ladies',
    image: '/chair-massage-ladies.jpg',
    serviceId: 's4',
    price: 210,
    availableGenders: ['Female'],
    rating: 4.4,
    reviews: 225,
  },
     {
    id: 'st10',
    name: 'Reflexology Massage',
    description: 'reflexology massage',
    image: '/reflexology-massage.jpeg',
    serviceId: 's4',
    price: 140,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.9,
    reviews: 125,
  },
     {
    id: 'st11',
    name: 'Massage',
    description: 'massage',
    image: '/massage.webp',
    serviceId: 's4',
    price: 150,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.3,
    reviews: 110,
  },
  ],
  Facial:[
{
    id: 'st16',
    name: 'Classic Facial',
    description: 'Classic facial',
    image: '/classic-facial.jpeg',
    serviceId: 's5',
    price: 150,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 3.6,
    reviews: 180,
  },
   {
    id: 'st17',
    name: 'Hydrating Facial',
    description: 'Hydrating facial',
    image: '/hydrating-facial.jpeg',
    serviceId: 's5',
    price: 180,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.6,
    reviews: 200,
  },
  {
    id: 'st18',
    name: 'Anti Aging Facial',
    description: 'Anti aging facial',
    image: '/anti-aging-facial.jpeg',
    serviceId: 's5',
    price: 180,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.6,
    reviews: 200,
  },
  ],
  Waxing:[
    {
      id: 'st14',
      name: 'soft-wax',
      description: 'soft-wax',
      image: '/soft-wax.jpeg',
      serviceId: 's6',
      price: 150,
      availableGenders: ['Male', 'Female', 'Unisex'],
      rating: 3.9,
      reviews: 180,
    },
    {
      id: 'st15',
      name: 'hard-wax',
      description: 'hard-wax',
      image: '/hard-wax.webp',
      serviceId: 's6',
      price: 150,
      availableGenders: ['Female', 'Unisex'],
      rating: 3.8,
      reviews: 180,
    },
  ]
}

export const styles: Style[] = [
  {
    id: 'st1',
    name: 'Classic Fade',
    description: 'Timeless fade with clean lines',
    image: '/style-classic-fade.jpg',
    serviceId: 's1',
    price: 450,
    availableGenders: ['Male', 'Unisex'],
    rating: 4.8,
    reviews: 245,
  },
  {
    id: 'st2',
    name: 'Textured Top',
    description: 'Modern textured cut with volume',
    image: '/style-textured.jpg',
    serviceId: 's1',
    price: 500,
    availableGenders: ['Male', 'Unisex'],
    rating: 4.7,
    reviews: 205,
  },
  {
    id: 'st3',
    name: 'Luxury Bob',
    description: 'Elegant bob cut for sophistication',
    image: '/style-bob.jpg',
    serviceId: 's1',
    price: 550,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.0,
    reviews: 145,
  },
  {
    id: 'st4',
    name: 'Balayage',
    description: 'Sun-kissed natural looking highlights',
    image: '/style-balayage.jpg',
    serviceId: 's2',
    price: 320,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.1,
    reviews: 145,
  },
  {
    id: 'st5',
    name: 'Blonde Highlights',
    description: 'Radiant blonde highlights',
    image: '/style-blonde.png',
    serviceId: 's2',
    price: 200,
    availableGenders: ['Female', 'Unisex'],
    rating: 3.9,
    reviews: 25,
  },
  {
    id: 'st6',
    name: 'Bridal Styling',
    description: 'Elegant styling for your special day',
    image: '/style-bridal.png',
    serviceId: 's3',
    price: 850,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.7,
    reviews: 247,
  },
  {
    id: 'st7',
    name: 'Evening Waves',
    description: 'Glamorous wavy styling for events',
    image: '/style-waves.jpg',
    serviceId: 's3',
    price: 550,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.2,
    reviews: 285,
  },
  {
    id: 'st8',
    name: 'Chair Massage',
    description: 'chair-massage-gents',
    image: '/chair-massage-gents.webp',
    serviceId: 's4',
    price: 150,
    availableGenders: ['Male'],
    rating: 4.8,
    reviews: 225,
  },
    {
    id: 'st9',
    name: 'Chair Massage',
    description: 'chair massage ladies',
    image: '/chair-massage-ladies.jpg',
    serviceId: 's4',
    price: 210,
    availableGenders: ['Female'],
    rating: 4.4,
    reviews: 225,
  },
     {
    id: 'st10',
    name: 'Reflexology Massage',
    description: 'reflexology massage',
    image: '/reflexology-massage.jpeg',
    serviceId: 's4',
    price: 140,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.9,
    reviews: 125,
  },
     {
    id: 'st11',
    name: 'Massage',
    description: 'massage',
    image: '/massage.webp',
    serviceId: 's4',
    price: 150,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.3,
    reviews: 110,
  },
  {
    id: 'st12',
    name: 'coloring men hair',
    description: 'coloring men hair',
    image: '/coloring-men-hair.png',
    serviceId: 's2',
    price: 150,
    availableGenders: [ 'Male'],
    rating: 4.3,
    reviews: 110,
  },
   {
    id: 'st13',
    name: 'coloring-hair',
    description: 'coloring-hair',
    image: '/coloring-hair.jpg',
    serviceId: 's2',
    price: 250,
    availableGenders: ['Female', 'Unisex'],
    rating: 4.1,
    reviews: 380,
  },
  {
    id: 'st14',
    name: 'soft-wax',
    description: 'soft-wax',
    image: '/soft-wax.jpeg',
    serviceId: 's6',
    price: 150,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 3.9,
    reviews: 180,
  },
    {
    id: 'st15',
    name: 'hard-wax',
    description: 'hard-wax',
    image: '/hard-wax.webp',
    serviceId: 's6',
    price: 150,
    availableGenders: ['Female', 'Unisex'],
    rating: 3.8,
    reviews: 180,
  },
 {
    id: 'st16',
    name: 'Classic Facial',
    description: 'Classic facial',
    image: '/classic-facial.jpeg',
    serviceId: 's5',
    price: 150,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 3.6,
    reviews: 180,
  },
   {
    id: 'st17',
    name: 'Hydrating Facial',
    description: 'Hydrating facial',
    image: '/hydrating-facial.jpeg',
    serviceId: 's5',
    price: 180,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.6,
    reviews: 200,
  },
  {
    id: 'st18',
    name: 'Anti Aging Facial',
    description: 'Anti aging facial',
    image: '/anti-aging-facial.jpeg',
    serviceId: 's5',
    price: 180,
    availableGenders: ['Male', 'Female', 'Unisex'],
    rating: 4.6,
    reviews: 200,
  },
   {
        id: 'st19',
        name: 'Wolf Cut',
        description: 'Elegant bob cut for sophistication',
        image: '/service-1.jpg',
        serviceId: 's1',
        price: 650,
        availableGenders: ['Unisex'],
        rating: 4.0,
        reviews: 145,
      },
];

export const salons: Salon[] = [
  {
    id: 'sal1',
    name: 'Luxe Salon & Spa',
    location: '123 Main Street, Downtown',
    image: '/salon-luxe.jpg',
    rating: 4.8,
    reviews: 245,
    openHours: { open: '09:00', close: '20:00' },
    services: ['s1', 's2', 's3', 's4', 's5', 's6'],
  },
  {
    id: 'sal2',
    name: 'Elite Barber Club',
    location: '456 Oak Avenue, Midtown',
    image: '/salon-elite.jpg',
    rating: 4.7,
    reviews: 189,
    openHours: { open: '10:00', close: '19:00' },
    services: ['s1', 's4'],
  },
  {
    id: 'sal3',
    name: 'Prestige Beauty Studio',
    location: '789 Park Road, Uptown',
    image: '/salon-prestige.jpg',
    rating: 4.9,
    reviews: 312,
    openHours: { open: '09:30', close: '20:30' },
    services: ['s1', 's2', 's3', 's5', 's6'],
  },
  {
    id: 'sal4',
    name: 'Refined Hair Design',
    location: '321 River Lane, North Side',
    image: '/salon-refined.jpg',
    rating: 4.6,
    reviews: 156,
    openHours: { open: '10:00', close: '18:00' },
    services: ['s1', 's2', 's3'],
  },
];

export const stylists: Stylist[] = [
  {
    id: 'sty1',
    name: 'Marcus Johnson',
    specializations: ['Haircut'],
    image: "",
    rating: 4.9,
    reviews: 87,
    salonId: 'sal1',
    genderSpecialization: 'Male',
  },
  {
    id: 'sty2',
    name: 'Sarah Chen',
    specializations: ['Coloring', 'Styling'],
    image: '',
    rating: 5.0,
    reviews: 124,
    salonId: 'sal1',
    genderSpecialization: 'Female',
  },
  {
    id: 'sty3',
    name: 'David Smith',
    specializations: ['Haircut', 'Styling'],
    image: '',
    rating: 4.7,
    reviews: 65,
    salonId: 'sal2',
    genderSpecialization: 'Male',
  },
  {
    id: 'sty4',
    name: 'Emma Wilson',
    specializations: ['Styling', 'Coloring'],
    image: '',
    rating: 4.8,
    reviews: 156,
    salonId: 'sal3',
    genderSpecialization: 'Female',
  },
  {
    id: 'sty5',
    name: 'James Rodriguez',
    specializations: ['Haircut'],
    image: '',
    rating: 4.6,
    reviews: 43,
    salonId: 'sal2',
    genderSpecialization: 'Male',
  },
  {
    id: 'sty6',
    name: 'Olivia Martinez',
    specializations: ['Facial', 'Massage'],
    image: '',
    rating: 4.9,
    reviews: 98,
    salonId: 'sal1',
    genderSpecialization: 'Female',
  },
];

export const timeSlots: TimeSlot[] = [
  {
    id: 'ts1',
    stylistId: 'sty1',
    date: '2025-02-25',
    time: '09:00',
    available: true,
    serviceId: 's1',
  },
  {
    id: 'ts2',
    stylistId: 'sty1',
    date: '2025-02-25',
    time: '10:00',
    available: true,
    serviceId: 's1',
  },
  {
    id: 'ts3',
    stylistId: 'sty1',
    date: '2025-02-25',
    time: '11:00',
    available: false,
    serviceId: 's1',
  },
  {
    id: 'ts4',
    stylistId: 'sty2',
    date: '2025-02-25',
    time: '14:00',
    available: true,
    serviceId: 's2',
  },
  {
    id: 'ts5',
    stylistId: 'sty2',
    date: '2025-02-25',
    time: '15:30',
    available: true,
    serviceId: 's2',
  },
  {
    id: 'ts6',
    stylistId: 'sty3',
    date: '2025-02-25',
    time: '13:00',
    available: true,
    serviceId: 's1',
  },
  {
    id: 'ts7',
    stylistId: 'sty4',
    date: '2025-02-25',
    time: '10:30',
    available: true,
    serviceId: 's3',
  },
];

export const mockUsers: User[] = [
  {
    id: 'u1',
    email: 'customer@example.com',
    name: 'John Doe',
    phone: '+1-555-0123',
    role: 'customer',
    bookings: [],
    createdAt: '2025-01-01',
  },
  {
    id: 'u2',
    email: 'admin@example.com',
    name: 'Admin User',
    phone: '+1-555-0124',
    role: 'admin',
    bookings: [],
    createdAt: '2025-01-01',
  },
];

export const plans = [
  {
    name: "Essential",
    price: "450",
    description: "Perfect for a quick refresh",
    features: [
      "Precision Haircut",
      "Blow Dry & Styling",
      "Scalp Massage",
      "Complimentary Beverage",
    ],
    highlighted: false,
  },
  {
    name: "Luxe",
    price: "220",
    description: "Our most popular package",
    features: [
      "Haircut & Styling",
      "Deep Conditioning Treatment",
      "Express Facial",
      "Hand & Nail Care",
      "Complimentary Refreshments",
    ],
    highlighted: true,
  },
  {
    name: "Bridal Suite",
    price: "650",
    description: "Your complete bridal experience",
    features: [
      "Bridal Hair & Makeup",
      "Trial Session Included",
      "Luxury Facial Treatment",
      "Full Body Spa",
      "Champagne & Treats",
      "Bridesmaid Discounts",
    ],
    highlighted: false,
  },
]

// Example service data - in production this would come from your state management (Jotai)
export const exampleService = [
  {
    id: 'wolf-cut',
    styleId: 'st19',
    serviceId: 's1',
    name: 'Wolf Cut',
    category: 'Hair Style',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/service-1.jpg',
      '/service-2.jpg',
      '/service-3.jpg',
      '/service-4.jpg',
      '/service-5.jpg'
    ],
    beforeImage: '/before.jpg',
    afterImage: '/after.jpg',
  },
  {
    id: 'Classic-Fade',
    styleId: 'st1',
    serviceId: 's1',
    name: 'Classic Fade',
    category: 'Hair Style',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/style-classic-fade.jpg',
      '/service-2.jpg',
      '/service-3.jpg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/style-classic-fade.jpg',
  },
  {
    id: 'textured-top',
    styleId: 'st2',
    serviceId: 's1',
    name: 'Textured Top',
    category: 'Hair Style',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/style-textured.jpg',
      '/service-2.jpg',
      '/service-3.jpg',
      '/service-4.jpg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/style-textured.jpg',
  },
  {
    id: 'luxury-bob',
    styleId: 'st3',
    serviceId: 's1',
    name: 'Luxury Bob',
    category: 'Hair Style',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/style-bob.jpg',
      '/service-2.jpg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/style-bob.jpg',
  },
  {
    id: 'luxury-bob',
    styleId: 'st4',
    serviceId: 's1',
    name: 'Luxury Bob',
    category: 'Hair Style',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/style-bob.jpg',
      '/service-2.jpg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/style-bob.jpg',
  },
  {
    id: 'Blonde Highlights',
    styleId: 'st5',
    serviceId: 's2',
    name: 'Blonde Highlights',
    category: 'Hair Style',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/style-blonde.png',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/style-blonde.png',
  },
  {
    id: 'Bridal Styling',
    styleId: 'st6',
    serviceId: 's3',
    name: 'Bridal Styling',
    category: 'Hair Style',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/style-bridal.png',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/style-bridal.png',
  },
  {
    id: 'Evening Waves',
    styleId: 'st7',
    serviceId: 's3',
    name: 'Evening Waves',
    category: 'Hair Style',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/style-waves.jpg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/style-waves.jpg',
  },
  {
    id: 'Chair Massage',
    styleId: 'st8',
    serviceId: 's4',
    name: 'Chair Massage',
    category: 'Massage',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/chair-massage-gents.webp',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/chair-massage-gents.webp',
  },
  {
    id: 'Chair Massage',
    styleId: 'st9',
    serviceId: 's4',
    name: 'Chair Massage',
    category: 'Massage',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/chair-massage-ladies.jpg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/chair-massage-ladies.jpg',
  },
  {
    id: 'Reflexology Massage',
    styleId: 'st10',
    serviceId: 's4',
    name: 'Reflexology Massage',
    category: 'Massage',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/reflexology-massage.jpeg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/reflexology-massage.jpeg',
  },
  {
    id: 'Massage',
    styleId: 'st11',
    serviceId: 's4',
    name: 'Massage',
    category: 'Massage',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/massage.webp',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/massage.webp',
  },
  {
    id: 'coloring men hair',
    styleId: 'st12',
    serviceId: 's2',
    name: 'coloring men hair',
    category: 'Hair coloring',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/coloring-men-hair.png',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/coloring-men-hair.png',
  },
  {
    id: 'coloring-hair',
    styleId: 'st13',
    serviceId: 's2',
    name: 'Coloring Hair',
    category: 'Coloring Hair',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/coloring-hair.jpg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/coloring-hair.jpg',
  },
  {
    id: 'soft-wax',
    styleId: 'st14',
    serviceId: 's6',
    name: 'Soft Wax',
    category: 'Waxing',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/soft-wax.jpeg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/soft-wax.jpeg',
  },
  {
    id: 'Hard Wax',
    styleId: 'st15',
    serviceId: 's6',
    name: 'Hard Wax',
    category: 'Waxing',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/hard-wax.webp',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/hard-wax.webp',
  },
  {
    id: 'Classic Facial',
    styleId: 'st16',
    serviceId: 's5',
    name: 'Classic Facial',
    category: 'Facial',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/classic-facial.jpeg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/classic-facial.jpeg',
  },
  {
    id: 'Hydrating Facial',
    styleId: 'st17',
    serviceId: 's5',
    name: 'Hydrating Facial',
    category: 'Facial',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/hydrating-facial.jpeg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/hydrating-facial.jpeg',
  },
  {
    id: 'Anti Aging Facial',
    styleId: 'st18',
    serviceId: 's5',
    name: 'Anti Aging Facial',
    category: 'Facial',
    rating: 4.7,
    reviewCount: 328,
    duration: '45 mins',
    price: 1200,
    description: 'The Wolf Cut is a modern, edgy hairstyle that combines the best of both mullets and shag cuts. It features longer layers on top with volume and movement, shorter sides, and a distinctive disconnected, textured look. Perfect for those seeking a bold, trendy transformation.',
    benefits: [
      'Modern trendy look that turns heads',
      'Versatile styling options - sleek or textured',
      'Works great for all hair types',
      'Long lasting results with minimal fading',
      'Easy maintenance between appointments',
      'Creates instant dimension and movement'
    ],
    suitableFor: 'Both',
    hairType: ['Straight', 'Wavy', 'Curly'],
    maintenanceLevel: 'Moderate',
    recommendedFrequency: '4-6 weeks',
    images: [
      '/anti-aging-facial.jpeg',
    ],
    beforeImage: '/before.jpg',
    afterImage: '/anti-aging-facial.jpeg',
  },
]

export const relatedServices = [
  { id: 'textured-fade', name: 'Textured Fade', category: 'Hair Cut', price: 800, image: '/related-1.jpg' },
  { id: 'undercut', name: 'Undercut', category: 'Hair Cut', price: 750, image: '/related-2.jpg' },
  { id: 'pompadour', name: 'Pompadour', category: 'Hair Style', price: 900, image: '/related-3.jpg' },
  { id: 'quiff', name: 'Quiff', category: 'Hair Style', price: 850, image: '/related-4.jpg' },
];